# Skill Sources Configuration
# 
# This file maintains a list of skills to import from other repositories.
# Each entry should specify:
#   - name: Local name for the skill (directory name)
#   - url: GitHub URL to the skill directory (tree view or API URL)
#   - enabled: Whether to import this skill (true/false)
#
# URL formats supported:
#   - GitHub tree URLs: https://github.com/user/repo/tree/branch/.github/skills/skill-name
#   - GitHub API URLs: https://api.github.com/repos/user/repo/contents/.github/skills/skill-name?ref=branch
#
# Example:
# skills:
#   - name: sync-job-expert
#     url: https://github.com/kehwar/frappe_tweaks/tree/main/.github/skills/sync-job-expert
#     enabled: true
#     description: Expert skill for working with Frappe sync jobs

skills:
  - name: doctype-schema-expert
    url: https://github.com/kehwar/frappe/tree/custom/.github/skills/doctype-schema-expert
    enabled: true
    description: Expert skill for working with Frappe DocType schemas
  - name: frappe-ci-expert
    url: https://github.com/kehwar/frappe/tree/custom/.github/skills/frappe-ci-expert
    enabled: true
    description: Expert guidance for CI/CD workflows in Frappe projects
  - name: bench-commands
    url: https://github.com/kehwar/frappe/tree/custom/.github/skills/bench-commands
    enabled: true
    description: Expert guidance for Frappe bench commands and operations
  - name: permissions-expert
    url: https://github.com/kehwar/frappe/tree/custom/.github/skills/permissions-expert
    enabled: true
    description: Expert guidance for Frappe permissions and access control
  - name: report-expert
    url: https://github.com/kehwar/frappe/tree/custom/.github/skills/report-expert
    enabled: true
    description: Expert guidance for Frappe reports and query reports
  - name: workflow-expert
    url: https://github.com/kehwar/frappe/tree/custom/.github/skills/workflow-expert
    enabled: true
    description: Expert guidance for Frappe workflows and workflow actions
  - name: frappe-hooks-expert
    url: https://github.com/kehwar/frappe/tree/custom/.github/skills/frappe-hooks-expert
    enabled: true
    description: Expert guidance for Frappe hooks and extension points
