# Copyright (c) 2026, Erick W.R. and contributors
# For license information, please see license.txt

import frappe
from frappe import _


def execute(filters=None):
    """
    Query Filters Report

    Lists all enabled Query Filter documents with their calculated SQL expressions.
    Useful for debugging and understanding how Query Filters are evaluated in different contexts.

    Filters:
        impersonate_user (optional): User to impersonate when calculating SQL.
            When set, the report switches to the specified user's context to calculate SQL,
            then switches back. This is useful for testing how filters evaluate for specific users,
            debugging permission-related issues, and understanding context-dependent filter behavior
            (e.g., Python filters using frappe.session.user).

    Columns:
        - Name: Link to the Query Filter document
        - Filter Name: Human-readable name of the filter
        - Reference DocType: The DocType this filter applies to (if any)
        - Reference Report: The Report this filter applies to (if any)
        - Reference Document: Specific document name (for single-record filters)
        - Type: Filter type (JSON, Python, or SQL)
        - Filter: Filter code definition (click "View Filter" button to see in dialog)
        - SQL: The SQL WHERE clause generated by the filter (line breaks removed for display)

    Features:
        - Only shows enabled Query Filters (disabled filters are excluded)
        - Calculates SQL in impersonated user context if specified
        - Error handling: Shows "ERROR: <message>" if SQL calculation fails
        - Original user context is always restored via finally block
        - Filter column includes "View Filter" button to display code in dialog

    Usage Examples:
        - View all enabled filters: Open report without filters
        - Test as another user: Set "Impersonate User" filter and refresh
        - Debug broken filters: Look for "ERROR:" prefix in SQL column

    Permissions:
        Requires System Manager role

    Related:
        - Query Filter DocType: tweaks/tweaks/doctype/query_filter/
        - AC Rule System: .github/instructions/ac-rule.instructions.md
    """
    columns = get_columns()
    data = get_data(filters)
    return columns, data


def get_columns():
    """Define report columns"""
    return [
        {
            "fieldname": "name",
            "label": _("Name"),
            "fieldtype": "Link",
            "options": "Query Filter",
            "width": 120,
            "hidden": 1,  # Hidden by default
        },
        {
            "fieldname": "filter_name",
            "label": _("Filter Name"),
            "fieldtype": "Data",
            "width": 200,
        },
        {
            "fieldname": "reference_doctype",
            "label": _("Reference DocType"),
            "fieldtype": "Link",
            "options": "DocType",
            "width": 150,
        },
        {
            "fieldname": "reference_report",
            "label": _("Reference Report"),
            "fieldtype": "Link",
            "options": "Report",
            "width": 150,
        },
        {
            "fieldname": "reference_docname",
            "label": _("Reference Document"),
            "fieldtype": "Data",
            "width": 150,
        },
        {
            "fieldname": "filters_type",
            "label": _("Type"),
            "fieldtype": "Data",
            "width": 100,
        },
        {
            "fieldname": "filters",
            "label": _("Filter"),
            "fieldtype": "Code",
            "width": 120,
        },
        {
            "fieldname": "sql",
            "label": _("SQL"),
            "fieldtype": "Data",
            "width": 500,
        },
    ]


def get_data(filters):
    """Fetch Query Filter data and calculate SQL for each"""

    # Get the impersonation user if specified
    impersonate_user = filters.get("impersonate_user") if filters else None
    original_user = frappe.session.user

    try:
        # Switch to impersonated user if specified
        if impersonate_user:
            frappe.set_user(impersonate_user)

        # Fetch all query filters (excluding disabled ones)
        query_filters = frappe.get_all(
            "Query Filter",
            filters={"disabled": 0},
            fields=[
                "name",
                "filter_name",
                "reference_doctype",
                "reference_report",
                "reference_docname",
                "filters_type",
                "filters",
            ],
            order_by="filter_name ASC, name ASC",
        )

        # Calculate SQL for each filter
        data = []
        for qf in query_filters:
            try:
                # Get the full document to calculate SQL
                filter_doc = frappe.get_doc("Query Filter", qf.name)
                sql = filter_doc.get_sql()
                # Remove line breaks from SQL
                sql = sql.replace("\n", " ").replace("\r", " ")
            except Exception as e:
                # If there's an error calculating SQL, show the error message
                sql = f"ERROR: {str(e)}"

            # Add calculated SQL to the row
            qf["sql"] = sql
            data.append(qf)

        return data

    finally:
        # Always switch back to the original user
        if impersonate_user and original_user:
            frappe.set_user(original_user)
