# Copyright (c) 2026, Erick W.R. and contributors
# For license information, please see license.txt

import frappe
from frappe import _


def execute(filters=None):
    """
    Query Filters Report

    Lists all enabled Query Filter documents with their calculated SQL expressions.
    Useful for debugging and understanding how Query Filters are evaluated in different contexts.

    Filters:
        preview_for_user (optional): User to evaluate filters for when calculating SQL.
            When set, the report calculates SQL as if the specified user is accessing the system.
            This is useful for testing how filters evaluate for specific users,
            debugging permission-related issues, and understanding context-dependent filter behavior
            (e.g., Python filters using the 'user' variable).

    Columns:
        - Name: Link to the Query Filter document
        - Filter Name: Human-readable name of the filter
        - Reference Type: Type of reference (Report or DocType)
        - Reference: The Report or DocType this filter applies to (clickable link)
        - Reference Document Name: Specific document name (for single-record filters, clickable link)
        - Type: Filter type (JSON, Python, or SQL)
        - Filter: Filter code definition (click "View Filter" button to see in dialog)
        - SQL: The SQL WHERE clause generated by the filter (line breaks removed for display)

    Features:
        - Only shows enabled Query Filters (disabled filters are excluded)
        - Calculates SQL in context of specified user if provided
        - Error handling: Shows "ERROR: <message>" if SQL calculation fails
        - Filter column includes "View Filter" button to display code in dialog

    Usage Examples:
        - View all enabled filters: Open report without filters
        - Test as another user: Set "Preview For User" filter and refresh
        - Debug broken filters: Look for "ERROR:" prefix in SQL column

    Permissions:
        Requires System Manager role

    Related:
        - Query Filter DocType: tweaks/tweaks/doctype/query_filter/
        - AC Rule System: .github/instructions/ac-rule.instructions.md
    """
    columns = get_columns()
    data = get_data(filters)
    return columns, data


def get_columns():
    """Define report columns"""
    return [
        {
            "fieldname": "name",
            "label": _("Name"),
            "fieldtype": "Link",
            "options": "Query Filter",
            "width": 120,
            "hidden": 1,  # Hidden by default
        },
        {
            "fieldname": "filter_name",
            "label": _("Filter Name"),
            "fieldtype": "Data",
            "width": 200,
        },
        {
            "fieldname": "reference_type",
            "label": _("Reference Type"),
            "fieldtype": "Data",
            "width": 120,
        },
        {
            "fieldname": "reference",
            "label": _("Reference"),
            "fieldtype": "Data",
            "width": 150,
        },
        {
            "fieldname": "reference_docname",
            "label": _("Reference Document Name"),
            "fieldtype": "Data",
            "width": 180,
        },
        {
            "fieldname": "filters_type",
            "label": _("Type"),
            "fieldtype": "Data",
            "width": 100,
        },
        {
            "fieldname": "filters",
            "label": _("Filter"),
            "fieldtype": "Code",
            "width": 120,
        },
        {
            "fieldname": "sql",
            "label": _("SQL"),
            "fieldtype": "Data",
            "width": 500,
        },
    ]


def get_data(filters):
    """Fetch Query Filter data and calculate SQL for each"""

    # Get the preview user if specified
    preview_user = filters.get("preview_for_user") if filters else None

    # Fetch all query filters (excluding disabled ones)
    query_filters = frappe.get_all(
        "Query Filter",
        filters={"disabled": 0},
        fields=[
            "name",
            "filter_name",
            "reference_doctype",
            "reference_report",
            "reference_docname",
            "filters_type",
            "filters",
        ],
        order_by="filter_name ASC, name ASC",
    )

    # Calculate SQL for each filter
    data = []
    for qf in query_filters:
        try:
            # Get the full document to calculate SQL
            filter_doc = frappe.get_doc("Query Filter", qf.name)
            # Use the user parameter if preview_user is specified
            sql = (
                filter_doc.get_sql(user=preview_user)
                if preview_user
                else filter_doc.get_sql()
            )
            # Remove line breaks from SQL
            sql = sql.replace("\n", " ").replace("\r", " ")
        except Exception as e:
            # If there's an error calculating SQL, show the error message
            sql = f"ERROR: {str(e)}"

        # Add calculated SQL to the row
        qf["sql"] = sql

        # Determine reference type and reference value
        if qf.get("reference_report"):
            qf["reference_type"] = "Report"
            qf["reference"] = qf["reference_report"]
        elif qf.get("reference_doctype"):
            qf["reference_type"] = "DocType"
            qf["reference"] = qf["reference_doctype"]
        else:
            qf["reference_type"] = None
            qf["reference"] = None

        data.append(qf)

    return data
